Query and update
KatIsCoding/vet_clinic_SQL pull request #3
Opened 2021-12-02 03:17 UTC by KatIsCoding

In this update more data is added to the database, a new property `species` is added to the schema and more queries using `group by` and aggregators are added

2021-12-02 05:28 UTC, oxenprogrammer requested changes
Hi @KatIsCoding, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
<FEEL FREE TO CHANGE THIS MESSAGE TO YOUR PERSONAL WORDS>


## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-12-02 05:28 UTC, oxenprogrammer commented on queries.sql
> +
**Changes Required**
You're missing some queries
- [ ] UPDATE the animals table by setting the species column to unspecified, then roll back the change.
- [ ] `UPDATE` the animals table by setting the species column to digimon for all animals that have a name ending in mon.
- [ ] `UPDATE` the animals table by setting the species column to pokemon for all animals that don't have species already set.
- [ ] Commit the transaction.
- [ ] Inside a transaction delete all records in the animals table, then roll back the transaction.
- [ ] `DELETE` all animals born after Jan 1st, 2022
- [ ] Create a savepoint for the transaction
- [ ] `UPDATE` all animals' weight to be their weight multiplied by -1.
- [ ] * Rollback to the savepoint
- [ ] `UPDATE` all animals' weights that are negative to be their weight multiplied by -1.
- [ ] Commit transaction

2021-12-02 05:28 UTC, oxenprogrammer commented on schema.sql
> +    species text,
**Changes Required**
- [ ] We shouldn't add the `species` column directly to the `animal` table but rather use the `ALTER` command to do so. Let us try and make these changes.

2021-12-03 16:04 UTC, emmanuellekamwa approved these changes
**STATUS: APPROVED 🍾🎉✔**
Hello @KatIsCoding 👋
Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-12-03 16:07 UTC, merged